# Generated by Django 4.2.4 on 2024-03-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
