# Generated by Django 4.2.4 on 2024-02-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_progress', '0002_designers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='designers',
            new_name='designer',
        ),
    ]
