# Generated by Django 4.2.4 on 2024-02-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_progress', '0003_rename_designers_designer'),
    ]

    operations = [
        migrations.CreateModel(
            name='progress_mile_stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mile_stone_name', models.CharField(max_length=50)),
                ('initial', models.CharField(max_length=10)),
                ('progress', models.DecimalField(decimal_places=5, max_digits=5)),
            ],
        ),
    ]
