# Generated by Django 4.2.4 on 2024-02-29 17:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('design_progress', '0005_alter_progress_mile_stone_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='filed_office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inital', models.CharField(max_length=15)),
                ('office_name', models.CharField(max_length=50)),
                ('xen', models.CharField(blank=True, max_length=40)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('progress', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
    ]
