# Generated by Django 4.2.4 on 2024-02-29 17:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('design_progress', '0006_filed_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filed_office',
            name='progress',
        ),
        migrations.AlterField(
            model_name='filed_office',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='filed_office',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='filed_office',
            name='xen',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
