# Generated by Django 4.2.4 on 2024-03-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_progress', '0007_remove_filed_office_progress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bwdb_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
            ],
        ),
    ]
