# Generated by Django 4.2.4 on 2024-03-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_progress', '0008_bwdb_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='bwdb_project',
            name='short_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
