# Generated by Django 4.2.4 on 2024-03-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_progress', '0009_bwdb_project_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bwdb_project',
            name='short_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
