# Generated by Django 4.2.4 on 2024-03-06 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_progress', '0010_alter_bwdb_project_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='design_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=350)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='design_progress.bwdb_project')),
            ],
        ),
    ]
