# Generated by Django 4.2.4 on 2024-03-06 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_progress', '0011_design_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='design_work',
            name='approver_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver_id', to='design_progress.designer'),
        ),
        migrations.AddField(
            model_name='design_work',
            name='checker_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checker_id', to='design_progress.designer'),
        ),
        migrations.AddField(
            model_name='design_work',
            name='designer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer_id', to='design_progress.designer'),
        ),
        migrations.AddField(
            model_name='design_work',
            name='division_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division', to='design_progress.filed_office'),
        ),
        migrations.AddField(
            model_name='design_work',
            name='reviewer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_id', to='design_progress.designer'),
        ),
        migrations.AlterField(
            model_name='design_work',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='design_progress.bwdb_project'),
        ),
    ]
