# Generated by Django 4.2.4 on 2024-03-06 20:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_progress', '0013_design_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='design_work_progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(default=datetime.datetime(2024, 3, 7, 2, 13, 51, 299413))),
                ('work_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='design_progress.design_work')),
                ('work_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='design_progress.progress_mile_stone')),
            ],
        ),
        migrations.DeleteModel(
            name='design_progress',
        ),
    ]
