# Generated by Django 4.2.4 on 2024-03-07 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('design_progress', '0014_design_work_progress_delete_design_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_work_progress',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
