# Generated by Django 4.2.4 on 2024-03-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_progress', '0016_designer_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design_work_progress',
            old_name='work_status',
            new_name='progress_status',
        ),
    ]
