# Generated by Django 4.2.4 on 2024-03-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_progress', '0017_rename_work_status_design_work_progress_progress_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='design_work_completion_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_status', models.CharField(max_length=50)),
                ('initial', models.CharField(max_length=10)),
            ],
        ),
    ]
