# Generated by Django 4.2.4 on 2024-03-18 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_progress', '0019_design_work_progress_work_completion_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design_work_progress',
            name='work_completion_status',
        ),
        migrations.AddField(
            model_name='design_work',
            name='work_completion_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completion_status', to='design_progress.design_work_completion_status'),
        ),
    ]
