# Generated by Django 4.2.4 on 2024-03-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_progress', '0020_remove_design_work_progress_work_completion_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design_work_progress',
            old_name='progress_status',
            new_name='work_status',
        ),
    ]
