# Generated by Django 4.2.4 on 2024-03-23 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_progress', '0021_rename_progress_status_design_work_progress_work_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='design_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='design_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_id', to='design_progress.design_work')),
            ],
        ),
    ]
