# Generated by Django 4.2.4 on 2024-03-23 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_doc_description'),
        ('design_progress', '0022_design_data_design_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='design_document',
            name='design_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_id', to='documents.document'),
        ),
    ]
