# Generated by Django 4.2.4 on 2024-03-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_progress', '0023_design_document_design_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design_document',
            old_name='design_document',
            new_name='document',
        ),
    ]
